# Generated by Django 4.0.2 on 2022-11-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_currency',
        ),
    ]
