# Generated by Django 4.1.3 on 2022-12-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0004_profile_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="sign",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
