# Generated by Django 4.1.3 on 2022-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0005_currency_sign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency", name="sign", field=models.CharField(max_length=5),
        ),
    ]
