# Generated by Django 4.0.2 on 2022-12-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0007_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='id_category',
        ),
    ]
