# Generated by Django 4.0.2 on 2022-12-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0008_remove_category_owner_remove_subcategory_id_category'),
        ('aplication', '0017_category_subcategory_alter_transaction_id_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
