# Generated by Django 4.1.3 on 2022-12-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0010_category_subcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="scope",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
