# Generated by Django 3.2.5 on 2023-03-18 14:12

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_test',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='images/default-user.png', null=True, upload_to='images/'),
        ),
    ]
