# Generated by Django 3.2.5 on 2023-03-18 14:18

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0015_profile_image_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_test',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='images/default-user.png', null=True, upload_to='images/'),
        ),
    ]
