# Generated by Django 4.1.3 on 2023-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0016_auto_20230318_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_transactions',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
