# Generated by Django 4.0.2 on 2022-11-23 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
        ('aplication', '0003_auto_20221104_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='User_Account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_currency',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id_account',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id_category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='id_subcategory',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id_transaction',
        ),
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UsersApp.profile'),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.profile'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
