# Generated by Django 4.1.3 on 2022-11-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplication", "0008_alter_account_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
