# Generated by Django 4.1.3 on 2022-12-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("UsersApp", "0006_alter_currency_sign"),
        ("aplication", "0011_account_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="UsersApp.currency",
            ),
        ),
    ]
