# Generated by Django 4.1.3 on 2022-12-03 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aplication", "0012_transaction_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="id_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aplication.category",
            ),
        ),
    ]
