# Generated by Django 4.1.3 on 2022-12-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aplication", "0013_transaction_id_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="aplication.category"
            ),
        ),
    ]
