# Generated by Django 4.1.3 on 2022-12-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0014_alter_transaction_id_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
