# Generated by Django 4.1.3 on 2022-12-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0019_remove_subcategory_id_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
