# Generated by Django 4.1.3 on 2022-12-06 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0012_alter_category_scope'),
        ('aplication', '0020_alter_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UsersApp.category'),
        ),
    ]
