# Generated by Django 3.2.5 on 2022-12-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0021_alter_transaction_id_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='name',
        ),
    ]
