# Generated by Django 4.1.3 on 2022-12-15 15:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0012_alter_category_scope'),
        ('aplication', '0022_remove_transaction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('access_level', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplication.account')),
                ('userFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='UsersApp.profile')),
                ('userTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to+', to='UsersApp.profile')),
            ],
        ),
    ]
