# Generated by Django 4.1.3 on 2022-12-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0023_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_periodic',
        ),
        migrations.AddField(
            model_name='transaction',
            name='repeat',
            field=models.CharField(choices=[('daily', 'Codziennie'), ('weekly', 'Co tydzień'), ('biweekly', 'Co 2 tygodnie')], default=None, max_length=50, null=True),
        ),
    ]
