# Generated by Django 4.1.3 on 2023-01-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0024_remove_transaction_is_periodic_transaction_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='repeat',
            field=models.CharField(blank=True, choices=[('daily', 'Codziennie'), ('weekly', 'Co tydzień'), ('biweekly', 'Co 2 tygodnie'), ('montly', 'Co miesiąc')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='access_level',
            field=models.CharField(choices=[('FULL', 'Pełny dostęp'), ('LIMITED', 'Ograniczony dostęp')], max_length=20),
        ),
    ]
