# Generated by Django 4.1.3 on 2023-01-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0025_alter_transaction_repeat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='access_level',
            field=models.CharField(choices=[('FULL', 'Pełny dostęp'), ('LIMITED', 'Ograniczony dostęp')], max_length=20),
        ),
    ]
