# Generated by Django 4.1.3 on 2023-02-28 00:12

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    MyModel = apps.get_model('aplication', 'Transaction')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    new_ct = ContentType.objects.get_for_model(MyModel)
    MyModel.objects.filter(polymorphic_ctype__isnull=True).update(polymorphic_ctype=new_ct)

class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('aplication', '0027_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
