# Generated by Django 4.1.3 on 2023-02-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0030_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='converted_amount',
        ),
    ]
