# Generated by Django 3.2.5 on 2022-11-04 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplication', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('User_Account', models.ManyToManyField(through='aplication.User_Account', to='aplication.Account')),
                ('id_currency', models.ForeignKey(default='PLN', on_delete=django.db.models.deletion.SET_DEFAULT, to='aplication.currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='user_account',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplication.profile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
