# Generated by Django 4.0.2 on 2022-11-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0003_remove_profile_id_currency'),
        ('aplication', '0004_remove_profile_user_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UsersApp.profile'),
        ),
    ]
